name: Update Mesh Metadata

on:
  push:
    paths:
      - "mesh/**"
    branches:
      - main
  workflow_dispatch: # allow manual trigger

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed for pushing changes

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Generate metadata and update README
        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python .github/scripts/update_mesh_metadata.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mesh/README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: update mesh agents table [skip ci]" && git push)
